"""central

Revision ID: 7624beecc879
Revises: bbb199b04ea4
Create Date: 2023-12-01 14:41:57.543912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7624beecc879'
down_revision: Union[str, None] = 'bbb199b04ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('isCentral', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'isCentral')
    # ### end Alembic commands ###
