"""Points decimal precision

Revision ID: a43a76d0c7fb
Revises: bd2d3e4cc13a
Create Date: 2023-10-30 18:13:43.176119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a43a76d0c7fb'
down_revision: Union[str, None] = 'bd2d3e4cc13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    op.create_table('Points',
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.Column('Longitude', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('Latitude', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('Value', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Points')
    op.create_table('points',
    sa.Column('ID', mysql.CHAR(length=32), nullable=False),
    sa.Column('Longitude', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('Value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
