"""init

Revision ID: bbb199b04ea4
Revises: 
Create Date: 2023-11-04 13:52:46.294753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb199b04ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('points',
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=15, scale=10), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    op.drop_table('couriers')
    # ### end Alembic commands ###
