"""Points table

Revision ID: bd2d3e4cc13a
Revises: 
Create Date: 2023-10-30 17:16:11.574646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd2d3e4cc13a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Points',
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.Column('Longitude', sa.Numeric(), nullable=True),
    sa.Column('Latitude', sa.Numeric(), nullable=True),
    sa.Column('Value', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('employers')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Name'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.create_table('employers',
    sa.Column('Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Name'),
    mariadb_collate='latin1_swedish_ci',
    mariadb_default_charset='latin1',
    mariadb_engine='InnoDB'
    )
    op.drop_table('Points')
    # ### end Alembic commands ###
