"""routes

Revision ID: da4bbb1425a4
Revises: 7624beecc879
Create Date: 2024-01-19 15:18:45.750892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4bbb1425a4'
down_revision: Union[str, None] = '7624beecc879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('ID', sa.Uuid(), nullable=False),
    sa.Column('courierId', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['courierId'], ['couriers.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.add_column('points', sa.Column('routeId', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'points', 'routes', ['routeId'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.drop_column('points', 'routeId')
    op.drop_table('routes')
    # ### end Alembic commands ###
